# Python Indentation

In [7]:
##### Indentation refers to the spaces at the beginning of a code line.
##### at least one space should be in the beginning of a code line

In [2]:
if(5>2):
    print("true")

true

In [5]:
if(5>2):
print("true")                    #####  if we miss identation it will show error

IndentationError: expected an indented block (<ipython-input-5-79917e40b43b>, line 2)

### python variable

In [9]:
# variables are created when you assign a value to it

### comment

In [10]:
 ######  you can add a multiline string (triple quotes) in your code, and place your comment inside it

In [11]:
"""   this os a comment
writttn in more than
one line"""

'   this os a comment\nwritttn in more than\none line'

##  casting

In [46]:
# casting is done using constructor function

In [1]:
### If you want to specify the data type of a variable, this can be done with casting.

In [48]:
###  it is also used to convert one data  type into another

x = str(3)    # x will be '3'
y = int(3)    # y will be 3
z = float(3)  # z will be 3.0

In [19]:
x =  9

In [20]:
x = str(9)

In [21]:
print(x)

9

In [22]:
x =float(9)

In [23]:
x

9.0

###  unpack a list

In [4]:
fruits = ["orange","banana","mango"]

In [5]:
x,y,z = fruits

In [6]:
print(x)

orange

In [7]:
print(y)

banana

In [9]:
print(z)

mango

###  to combine both text and variable python uses + sign

### to combine both string and number you will see an error

### Global Variables

In [1]:
x = "awesome"

def myfunc():
  print("Python is " + x)

myfunc()

Python is awesome

In [2]:
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()

print("Python is " + x)

Python is fantastic
Python is awesome

In [3]:
def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic

In [2]:
### square brackets can be used to access the elements of the string

In [1]:
a  ='hello world'

In [8]:
print(a[2])

l

### loop

for x in "banana":
     print(x)

### length

In [12]:
len(x)

1

In [13]:
len(a)

11

In [15]:
txt = "I am a super hero"

In [24]:
###  in gives true or false

### to check --------"in" is used

In [25]:
###  if print whatever you write in print functionas below

In [17]:
print("am"  in  txt)

True

### ------   if

In [22]:
text = "I am an old man"

In [23]:
if "am" in text:
    print("yes")

yes

### slicing

In [ ]:
###  gives range f characters or integers

In [2]:
print(a[2:4])

ll

In [3]:
print(a[:4])

hell

In [4]:
print(a[2:])

llo world

In [6]:
print(a[-5:-3])

wo

###  modify strings

In [7]:
print(a.upper())

HELLO WORLD

In [8]:
print(a.lower())

hello world

In [9]:
####  to remove whitespace

In [13]:
a  = "    hello, world!    "

In [14]:
a.strip()

'hello, world!'

In [15]:
#####  replace string letters

In [17]:
print(a.replace("h" , "J"))

    Jello, world!

In [18]:
### split string

In [19]:
### The split() method returns a list where the text between the specified separator becomes the list items

In [21]:
print(a.split())

['hello,', 'world!']

### string format

In [23]:
### we can not combine string and integer

In [24]:
#  but we can combine string and number by  format method

In [25]:
age = 45

text1 = "I am a super boy,and I am {}"

In [29]:
print(text1.format(age))

I am a super boy,and I am 45

In [34]:
 itemnumber = 123
 quantity = 1234
 price = 234

In [37]:
text2 ="the product itemnumber is {},it's quantity is {} and its price is $ {}"

In [38]:
print(text2.format(itemnumber,quantity,price))

the product itemnumber is 123,it's quantity is 1234 and its price is $ 234

### escape character

In [41]:
#     text3 = "We are the so-called "Vikings" from the north."------------------error

In [42]:
#   to not get error we need to use the symbol  ----- \"

In [45]:
text3= "We are the so-called \"Vikings\" from the north."

# booleans

In [1]:
# booleans represent two values - "true"  or "false"

In [2]:
# when we compare the two expressions we get the result as true or false

In [3]:
print(10>9)

True

In [4]:
# when we run a condition in an if statement the result is obtained as true or false

In [5]:
a = 20
b = 1
if(b>a):
    print("it is true")
else:
     print("it is not")

it is not

In [6]:
print(bool("hello"))

True

In [7]:
print(bool(15))

True

In [8]:
x = "hello"           ## give true when used in bool

In [9]:
y = 13                  ## give true when used in bool

In [10]:
bool(x)

True

In [11]:
##  most values are returned as true

In [12]:
# almost any value is returned as true ifit has some sor of content

In [13]:
# any string is true , except empty string

In [14]:
# any number is true except 0

In [15]:
# any list,tuples ,set , dictionaries are true except ones

In [16]:
bool("")

False

In [17]:
bool(0)

False

In [22]:
bool([])

False

In [19]:
##       class_len_ will also give false

In [28]:
class myclass():
    def _len_(self):
       return 0
myobj = myclass()
print(bool(myobj))

True

In [29]:
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

False

In [30]:
def myfunc():
    return true
print(bool("myfunc"))

True

In [3]:
def myFunction() :
  return True

if myFunction():
  print("YES!")
else:
  print("NO!")

YES!

In [4]:
#to check if an object is of certain data type or not ---  isinstance()

In [5]:
x = 200
print(isinstance(x,int))

True

## python operators

In [6]:
# modulus

In [5]:
x = 24
y = 4

In [6]:
x % y

0

In [7]:
# exponenation

In [9]:
x**y

331776

In [11]:
#  floor- x//y

In [10]:
x//y         #The floor() method returns the floor of x i.e. the largest integer not greater than x.

6

In [1]:
##  and operator --   returns true if both statements are true

In [2]:
## or operator --  returns true if only one statement is true

In [3]:
##  not operator -- returns true if statments is false  and revers

In [4]:
x = 3
print(x>2 and x<12)

True

In [12]:
x = 4
print(x < 3 or x == 4)

True

In [13]:
x = 4 
print(not(x > 3 and x < 10))

False

In [15]:
# in operator ---returns true if a specified value is present in a object
# not in ---returns true if a specified value is not present in  a  object

In [18]:
x = "string"

print("rin" in x)

True

## list

In [1]:
# list  can hold 4 data types of python i.e, data,tuple,set,dictionary

In [2]:
# list are creaated in square brackets

In [26]:
## lists can be changed

In [3]:
thislist = ['apple','banana','orange']

In [4]:
print(thislist)

['apple', 'banana', 'orange']

In [8]:
# list items are changeable and allow duplicate values to come again and execute
#  list items are ordered i.e, it will not change when we add a new item to a list  rather it will be added at the end ofthe list
# to determine number ofitems in a list use len()
# list can contain any data type i.e, int , boolean , string

In [9]:
# to construct a string in a list use -----    (())

In [10]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

['apple', 'banana', 'cherry']

### python collection arrays

In [11]:
#There are four collection data types in the Python programming language:

#List is a collection which is ordered and changeable. Allows duplicate members.
#Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
#Set is a collection which is unordered and unindexed. No duplicate members.
#Dictionary is a collection which is unordered and changeable. No duplicate members.

### access items

In [12]:
# -1 , -2 ,refers to the  last and the second last items

In [14]:
thislist = ["apple", "banana", "cherry"]
print(thislist[-1])

cherry

In [25]:
list = ["mango", "apple", "banana","pineapple",23,"@"]

In [27]:
print(list[2:5])

['banana', 'pineapple', 23]

In [28]:
#The search will start at index 2 (included) and end at index 5 (not included).

##  check if items exist

In [29]:
list = ["mango", "apple", "banana","pineapple",23,"@"]
if "@" in list:
    print("yes")

yes

### change item view

In [30]:
list = ["mango", "apple", "banana","pineapple",23,"@"]

In [32]:
list[2] = "blackapple"

In [33]:
print(list)

['mango', 'apple', 'blackapple', 'pineapple', 23, '@']

In [34]:
list[2:4] =  ["apple2","apple3","apple4"]

In [35]:
print(list)

['mango', 'apple', 'apple2', 'apple3', 'apple4', 23, '@']

In [36]:
### Insert Items
### To insert a new list item, without replacing any of the existing values, we can use the insert() method.

In [37]:
list = ["mango", "apple", "banana","pineapple",23,"@"]
list.insert(2,"guava")

In [38]:
print(list)

['mango', 'apple', 'guava', 'banana', 'pineapple', 23, '@']

In [39]:
## # to add an item at the end of the list use "append"

In [40]:
list.append("watermelon")

In [41]:
print(list)

['mango', 'apple', 'guava', 'banana', 'pineapple', 23, '@', 'watermelon']

In [42]:
## Extend List
## To append elements from another list to the current list, use the extend() method.

In [43]:
list = ["mango", "apple", "banana","pineapple",23,"@"]
tropical = ["hippo","zebra","cobra"]

In [46]:
list.extend(tropical)

In [47]:
print(list)

['mango', 'apple', 'banana', 'pineapple', 23, '@', 't', 'r', 'o', 'p', 'i', 'c', 'a', 'l', 'hippo', 'zebra', 'cobra']

In [48]:
###  remove  specified elements from a list

In [3]:
list = ["mango", "apple", "banana","pineapple",23,"@"]
list.remove("banana")
print(list)

['mango', 'apple', 'pineapple', 23, '@']

In [4]:
# Remove Specified Index
# The pop() method removes the specified index.

In [5]:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

['apple', 'cherry']

In [9]:
#Remove the last item:

thislist = ["apple", "banana", "cherry"]
thislist.pop()
print(thislist)

['apple', 'banana']

In [7]:
#  del removes speccified  items from  list

In [14]:
thislist = ["apple", "banana", "cherry"]
del thislist[0]
print(thislist)

['banana', 'cherry']

In [15]:
thislist = ["apple", "banana", "cherry"]
for x in thislist:
    print(x)

apple
banana
cherry

### Iterable is an object, which one can iterate over. It generates an Iterator when passed to iter() method. Iterator is an object, which is used to iterate over an iterable object using __next__() method. ... Note that every iterator is also an iterable, but not every iterable is an iterator.

In [16]:
## to create iterator

In [6]:
#  iterabble can iterate objects onlylike list,tuple,set,etc.

In [18]:
# use range()  and len()  function to create iterable

In [21]:
nums = [7,6,5,4]
it = iter(nums)         # iter == iterator
print(it)

print(next(it))
print(next(it))

<list_iterator object at 0x7f1602de3a90>
7
6

In [9]:
newlist =[x for x in range(10) if x<5]
print(newlist)

[0, 1, 2, 3, 4]

In [19]:
thislist = ["apple", "banana", "cherry"]
for i in range(len(thislist)):
    print(thislist[i])

apple
banana
cherry

In [20]:
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
    print(thislist[i])
    i = i + 1

apple
banana
cherry

In [3]:
thislist = ["apple", "banana", "cherry"]
newlist = [x for x in thislist if x != "apple"]
print(newlist)

['banana', 'cherry']

##  sort

In [6]:
# it wil sort()  the list alphanumerically by default in ascending order

In [8]:
thislist = ["apple", "banana", "cherry"]
thislist.sort()
print(thislist)

['apple', 'banana', 'cherry']

In [9]:
thislist2 = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist2.sort()
print(thislist2)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']

In [11]:
thislist2 = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist2.sort(reverse = True)
print(thislist2)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']

In [13]:
###  customize sort function

In [15]:
###  to customize your own sort function use key = function
###  the function will return a list that will be used to sort the list(the lowest number first)

In [17]:
def myfunc(n):
    return abs(n-50)
thislist = [100,90,80,70,60]
thislist.sort( key = myfunc)
print(thislist)

[60, 70, 80, 90, 100]

In [18]:
##  join list

In [22]:
list1 = [1,2,3]
list2 = ["a","b","c"]
list3 = list2 + list1
print(list3)

['a', 'b', 'c', 1, 2, 3]

 for x in list2:
 list1.append(x)
 print(list1)

In [23]:
list1.extend(list2)
print(list1)

[1, 2, 3, 'a', 'b', 'c']

## tuples

In [25]:
## A tuple is a collection which is ordered and unchangeable.
# Tuples are written with round brackets.

In [28]:
thistuple = ("apple", "mango","banana")
print(thistuple)

('apple', 'mango', 'banana')

In [32]:
#type of tuple

In [34]:
tuple=("apple",)
print(type(tuple))

<class 'tuple'>

In [1]:
##  creating tuple with one item ,then, we have to add comma after the item otherwisepython will not recogniseit as a tuple

In [35]:
## not a tuple
thistuple1 = ("apple")

In [36]:
print(type(thistuple1))

<class 'str'>

In [2]:
###  to construct tuple
thistuple = tuple(("apple", "banana", "cherry")) # note the double round-brackets
print(thistuple)

('apple', 'banana', 'cherry')

In [4]:
## Python Collections (Arrays)
## There are four collection data types in the Python programming language:

#List is a collection which is ordered and changeable. Allows duplicate members.
#Tuple is a collection which is ordered and unchangeable. Allows duplicate members.
#Set is a collection which is unordered and unindexed. No duplicate members.
#Dictionary is a collection which is unordered and changeable. No duplicate members.

In [5]:
###  change tuple value

In [7]:
x = ("apple", "banana","mango")
y = list(x)
y[1] = "kiwi"
y = tuple(y)
print(y)

('apple', 'kiwi', 'mango')

In [11]:
#  y.append("kiwa")
#print(y)

In [6]:
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
['cherry', 'strawberry', 'raspberry']

In [2]:
thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

apple
banana
cherry

In [7]:
fruits.count("apple")      ####  returns the specified number of times a specified vlaue occurs

1

In [10]:
fruits.index("cherry")   ###  returns the position of the specified vslue ask

2

## sets

In [11]:
## sets are written with curly brackets

In [14]:
theset ={"apple","apple", "banana"}
print(theset)

{'banana', 'apple'}

In [15]:
##  to construct a set

In [18]:
theset2 = set(("apple","apple", "banana"))
print(theset2)

{'banana', 'apple'}

In [19]:
theset2.add("orange")
print(theset2)

{'banana', 'orange', 'apple'}

In [20]:
###  to add items from another set to current set use "update" method

In [21]:
theset2.update(theset)

In [22]:
print(theset2)

{'orange', 'apple', 'banana'}

In [23]:
##  to remove one item of a set use discard

In [25]:
theset2.discard("banana")
print(theset2)

{'orange', 'apple'}

In [26]:
##  using pop() function removes the last item of the set

In [27]:
thisset = {"apple", "banana", "cherry"}
x = thisset.pop()

In [29]:
print(x)

banana

In [37]:
for x in theset:
    print(x)

banana
apple

In [36]:
theset ={"apple","apple", "banana"}

###  join two sets

In [38]:
####  use union function to join the set

In [41]:
set1 = {1,2,3}
set2 ={5,6,7}
x = set1.union(set2)
print(x)

{1, 2, 3, 5, 6, 7}

In [44]:
x = set1.update(set2) 
print(x)

None

In [45]:
## Keep ONLY the Duplicates

In [48]:
theset2 = {"apple","mango"}

In [49]:
y = theset.intersection_update(theset2)
print(y)

None

In [51]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.intersection_update(y)
print(x)

{'apple'}

In [52]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection(y)

print(z)

{'apple'}

In [53]:
#  Keep All, But NOT the Duplicates

In [54]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}
x.symmetric_difference_update(y)
print(x)

{'google', 'banana', 'cherry', 'microsoft'}